### ISSUE TITLE
Add a print method?

### ISSUE THREAD

**Issue by leeper** [RL10N/poio#11]
It might be nice to have a simpler print method for this, which quickly summarizes the contents. What do you think?

**Comment by richierocks** [comment]
I drafted a print method in the master branch. Then decided that it might be showing too much boring stuff, and stripped down the method further in the `simple-print` branch. 

I think we need both a stripped down display form and an everything display form.

The modelling functions like `lm` have a very minimal `print` method and a more verbose `summary` method.

Vectors and data frames work the other way around, with `print` showing everything and `summary` showing less. This makes a bit more sense to me intuitively, but I don't know what the best practice is.

**Comment by leeper** [comment]
Thanks! I agree, let's have a `summary()` method that does the simple printing.

**Comment by richierocks** [comment]
`print` and `summary` now in a form I'm reasonably happy with.

**Comment by leeper** [comment]
Thanks!

PS poio is really, really awesome. It was such a breeze to integrate it into msgtools.

**Comment by richierocks** [comment]
Thanks!

Just looking at your updates to msgtools now. Very nice so far. Are there any issues you want me to work on?

**Comment by leeper** [comment]
I don't think so. I'll try to get a first cut on CRAN by the weekend. Really just need to finish the vignette and add tests at this point.
