### ISSUE TITLE
Piping error

### ISSUE THREAD

**Issue by leeper** [RL10N/poio#13]
I was getting an unused argument error in `fix_metadata()`, but correcting it (see PR: https://github.com/RL10N/poio/tree/fix-piping) appears to have broken some tests but I'm not sure why.

**Comment by leeper** [comment]
Okay, odd, it passed on Travis so maybe it was just a fluke on my system.

**Comment by richierocks** [comment]
The tests weren't broken on my machine, but it definitely looked like a bug. I've merged your fix into master. Thanks!
