### ISSUE TITLE
Make it possible to override whoami?

### ISSUE THREAD

**Issue by leeper** [RL10N/poio#16]
I think this line: https://github.com/RL10N/poio/blob/master/R/fix_metadata.R#L194-L198 is causing msgtools to [fail on Solaris](https://cran.r-project.org/web/checks/check_results_msgtools.html). Is there a way currently to overide the calls to whoami functions?

**Comment by richierocks** [comment]
I guess I can make `whoami` a suggested package or have setting the Last-Translator field OS-specific. And bring the issue up with Gabor Csardi to see if he can provide a fix in `whoami`.

**Comment by leeper** [comment]
Or, can you just add function arguments so I can have msgtools require explicit values for those fields?

**Comment by richierocks** [comment]
Good idea. I'll take a look at it this evening.

**Comment by richierocks** [comment]
Fixed via 563882bdec9caed1b93a0bf26a836f6b4a9cb3f2 through to fc2eaff2302352d937f84b0d7caf51c5f0dd4b4c

**Comment by richierocks** [comment]
Please can you double check that this solves your problems. If it doesn't work for you, I'll reopen and have another go.

**Comment by leeper** [comment]
Yes, this works. Thanks!
