### ISSUE TITLE
Special language name for directional quotes in UTF-8

### ISSUE THREAD

**Issue by leeper** [RL10N/poio#18]
In order to accommodate the "language" `en@quot` (see [Translation guide](https://github.com/RL10N/poio/blob/master/R/language_codes-dataset.R#L59)), which provides directional quotes in UTF-8, `ALLOWED_LANGUAGE_REGEX` needs accommodate `en@quot` as an allowed value.

**Comment by leeper** [comment]
Nevermind actually.

**Comment by richierocks** [comment]
@leeper That sounds like a sensible idea; why did you change your mind?

Any do you know if it is only `en@quot`, or can any language have an `@quot` suffix? For example, is `fr@quot` acceptable?

**Comment by leeper** [comment]
It turns out `gettext` freaks out if you try to pass `en@quot` as a language value, so it seems better to keep this as an R-level error.

The translation functionality in `tools::update_pkg_po()` has a bunch of hacks to get around this (post-processing the files); so I more or less just copied the basic idea from there in msgtools.
